<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-RNGQG4M" name="com.envision.test.tests.DemoTest" tests="1" failures="0" timestamp="29 May 2021 15:24:13 GMT" time="14.152" errors="1">
  <testcase name="loginScenarioNegative" time="14.152" classname="com.envision.test.tests.DemoTest">
    <error type="org.junit.ComparisonFailure" message="expected:&lt;rgb[(241, 51, 64])&gt; but was:&lt;rgb[a(241, 51, 64, 1])&gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<rgb[(241, 51, 64])> but was:<rgb[a(241, 51, 64, 1])>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at com.envision.test.pages.LoginPage.validateErrorHighlightOnUserName(LoginPage.java:44)
	at com.envision.test.tests.DemoTest.loginScenarioNegative(DemoTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- loginScenarioNegative -->
</testsuite> <!-- com.envision.test.tests.DemoTest -->
